modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="packmenu" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Pack Menu" #mandatory

description='''
Adds the ability to change the background of the main menu, as well as edit some other menu-related things.
'''

[[dependencies.packmenu]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33.0.22,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.packmenu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packmenu]]
    modId="placebo"
    mandatory=true
    versionRange="[4.2,)"
    ordering="NONE"
    side="BOTH"